(define (make-monitored f)
  (let ((counter 0))
    (define (mf op)
      (cond ((eq? op 'how-many-calls?)
             counter)
            ((eq? op 'reset-count)
             (begin (set! counter 0)
                    counter))
            (else (begin (set! counter (+ counter 1))
                         (f op)))))
    mf))
